version: '3.7'
services:
  app:
    build:
      context: .
    environment:
      RAILS_ENV: development
    ports:
      - "3001:3000"
    volumes:
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/unicorn.rb:/app/config/unicorn.rb
    command: bundle exec rails server -b 0.0.0.0 -p 3000 
  
  db:
    image: mysql:5.7-debian  # Add this line
    environment:
      MYSQL_ROOT_PASSWORD: smart
      MYSQL_DATABASE: smart
      MYSQL_USER: smart
      MYSQL_PASSWORD: smart
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro

  # nginx:
  #   image: nginx  # Add this line
  #   environment:
  #     SVA_COMMUNITY: int-development
  #     VOLUME_LOCALTIME: "unused:/unused"
  #   volumes:
  #     - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - "8080:80"
  #   labels:
  #     - traefik.enable=true
  #     - traefik.docker.network=public
  #     - traefik.frontend.rule=Host:server.smart-village.docker.localhost
  #   depends_on:
  #     - app
  #   networks:
  #     - default
  #     - public
  

# networks:
#   public:
#     external: true
