version: '3.7'

services:
  delayed_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver
    command: bin/delayed_job start
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
    depends_on: [db]
    deploy:
      restart_policy:
        condition: on-failure

  cron_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver
    command: bin/start-cron.sh
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
    depends_on: [db]
    deploy:
      restart_policy:
        condition: on-failure

  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    depends_on: [app]
    ports:
      - "8080:80"
    configs:
      - source: smart-village-app-mainserver-nginx-conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/public
    labels:
      - traefik.frontend.rule=Host:smartvillage.app
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: mysql:5.7-debian
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=1000
    environment:
      MYSQL_ROOT_PASSWORD: smart
      MYSQL_DATABASE: smart
      MYSQL_USER: smart
      MYSQL_PASSWORD: smart
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db:
  unicorn:
  assets:

